SELECT E.EMPLOYEE_ID, E.NAME,
COUNT(E.EMPLOYEE_ID) AS REPORTS_COUNT,
ROUND(AVG(M.AGE)) AS AVERAGE_AGE
FROM EMPLOYEES AS E
JOIN EMPLOYEES AS M
WHERE M.REPORTS_TO = E.EMPLOYEE_ID
GROUP BY E.EMPLOYEE_ID
ORDER BY 1